# This is a basic workflow to make the documentation and update its GitHub page automatically.
name: Build-docs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  build_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install ${{ matrix.pip-flags }} ".[docs]"
      - name: Build HTML
        run: |
          cd doc/
          make clean
          make html
      - name: Run ghp-import
        run: |
          ghp-import -n -p -f docs/_build/html