name: Grad-Learn

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
  test:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.11"]

    steps:
        - uses: actions/checkout@v3
        - name: Set up Python ${{ matrix.python }}
          uses: actions/setup-python@v4
          with:
              python-version: "3.11"
              cache: "pip"
              cache-dependency-path: "**/pyproject.toml"
        - name: Install dependencies
          run: |
              python -m pip install --upgrade pip wheel
              pip install ${{ matrix.pip-flags }} ".[dev]"
        - name: Test
          run: |
              pytest -v --cov --color=yes
